In [1]:
# import pandas and load the first sheet "Nuclear consumption"
import pandas as pd
Nuclear_consumption = pd.read_excel("C:/Users/pc/Desktop/+++/2ème année Génie Chimique/S3/Raffinage du pétrole (4)/séminaire/sources utilisées/done/bp-stats-review-2022-all-data.xlsx", sheet_name='Nuclear Consumption - EJ', header=None)

In [2]:
Nuclear_consumption.head(10)

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,Nuclear: Consumption*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Growth rate per annum,NaN,Share
2,Exajoules (input-equivalent),1965.000000,1966.000000,1967.000000,1968.000000,1969.000000,1970.000000,1971.000000,1972.000000,1973.000000,...,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2021,2011-21,2021
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Canada,0.001308,0.001757,0.001563,0.009377,0.005404,0.010593,0.043588,0.073661,0.155820,...,0.940541,0.931486,0.924823,0.914263,0.915107,0.884696,0.831268,-0.057817,-0.006322,0.03284
5,Mexico,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.107702,0.097725,0.100052,0.123889,0.101896,0.101413,0.107778,0.065671,0.011483,0.004258
6,US,0.039319,0.059354,0.082314,0.134714,0.149762,0.234456,0.409726,0.581625,0.897629,...,7.806465,7.843175,7.789835,7.764820,7.758474,7.543456,7.404259,-0.015764,-0.006798,0.29251
7,Total North America,0.040627,0.061111,0.083877,0.144092,0.155165,0.245049,0.453314,0.655286,1.053449,...,8.854708,8.872385,8.814710,8.802971,8.775477,8.529565,8.343304,-0.019157,-0.006536,0.329608
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Argentina,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.065484,0.076619,0.055970,0.062809,0.076883,0.096736,0.097911,0.014919,0.048471,0.003868

In [3]:
print(Nuclear_consumption.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       113 non-null    object
 1   1       104 non-null    float64
 2   2       104 non-null    float64
 3   3       104 non-null    float64
 4   4       104 non-null    float64
 5   5       104 non-null    float64
 6   6       104 non-null    float64
 7   7       104 non-null    float64
 8   8       104 non-null    float64
 9   9       104 non-null    float64
 10  10      104 non-null    float64
 11  11      105 non-null    object
 12  12      104 non-null    float64
 13  13      104 non-null    float64
 14  14      104 non-null    float64
 15  15      104 non-null    float64
 16  16      104 non-null    float64
 17  17      104 non-null    float64
 18  18      104 non-null    float64
 19  19      104 non-null    float64
 20  20      104 non-null    float64
 21  21      104 non-null    float64
 22  22      104 non-null    float64
 23  23      104 non-null    float64
 24  24      104 non-null    float64
 25  25      104 non-null    float64
 26  26      104 non-null    float64
 27  27      104 non-null    float64
 28  28      104 non-null    float64
 29  29      104 non-null    float64
 30  30      104 non-null    float64
 31  31      104 non-null    float64
 32  32      104 non-null    float64
 33  33      104 non-null    float64
 34  34      104 non-null    float64
 35  35      104 non-null    float64
 36  36      104 non-null    float64
 37  37      104 non-null    float64
 38  38      104 non-null    float64
 39  39      104 non-null    float64
 40  40      104 non-null    float64
 41  41      104 non-null    float64
 42  42      104 non-null    float64
 43  43      104 non-null    float64
 44  44      104 non-null    float64
 45  45      104 non-null    float64
 46  46      104 non-null    float64
 47  47      104 non-null    float64
 48  48      104 non-null    float64
 49  49      104 non-null    float64
 50  50      104 non-null    float64
 51  51      104 non-null    float64
 52  52      104 non-null    float64
 53  53      104 non-null    float64
 54  54      104 non-null    float64
 55  55      104 non-null    float64
 56  56      104 non-null    float64
 57  57      104 non-null    float64
 58  58      105 non-null    object
 59  59      104 non-null    object
 60  60      105 non-null    object
dtypes: float64(56), object(5)
memory usage: 58.7+ KB
None

In [4]:
print(Nuclear_consumption.describe())

                1            2            3            4            5   \
count   104.000000   104.000000   104.000000   104.000000   104.000000
mean     18.904711    18.917922    18.930220    18.944300    18.958090
std     192.683070   192.780776   192.878572   192.976194   193.073846
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000     0.000000
50%       0.000000     0.000000     0.000000     0.000000     0.000000
75%       0.000000     0.000000     0.000000     0.000000     0.000000
max    1965.000000  1966.000000  1967.000000  1968.000000  1969.000000

                6            7            8            9            10  ...  \
count   104.000000   104.000000   104.000000   104.000000   104.000000  ...
mean     18.974945    18.997178    19.024695    19.055200    19.090099  ...
std     193.171200   193.268045   193.364397   193.460501   193.556229  ...
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...
75%       0.000000     0.000000     0.000051     0.000470     0.005078  ...
max    1970.000000  1971.000000  1972.000000  1973.000000  1974.000000  ...

                48           49           50           51           52  \
count   104.000000   104.000000   104.000000   104.000000   104.000000
mean     20.320265    20.330648    20.353298    20.366968    20.382666
std     197.224414   197.322482   197.419773   197.517326   197.614837
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000     0.000000
50%       0.000000     0.000000     0.000000     0.000000     0.000000
75%       0.214414     0.209102     0.202418     0.206009     0.201958
max    2012.000000  2013.000000  2014.000000  2015.000000  2016.000000

                53           54           55           56           57
count   104.000000   104.000000   104.000000   104.000000   104.000000
mean     20.393908    20.420123    20.459868    20.422782    20.469901
std     197.712614   197.809725   197.906177   198.006059   198.102156
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000     0.000000
50%       0.000000     0.000000     0.000000     0.000000     0.000000
75%       0.202091     0.213670     0.225365     0.216171     0.219340
max    2017.000000  2018.000000  2019.000000  2020.000000  2021.000000

[8 rows x 56 columns]

In [ ]:
print(Nuclear_consumption.isnull().sum())

0     10
1     19
2     19
3     19
4     19
      ..
56    19
57    19
58    18
59    19
60    18
Length: 61, dtype: int64

In [ ]:
#Dropping the empty rows using dropna()
Nuclear_cons = Nuclear_consumption.dropna()
Nuclear_cons.head(10)

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
2,Exajoules (input-equivalent),1965.000000,1966.000000,1967.000000,1968.000000,1969.000000,1970.000000,1971.000000,1972.000000,1973.000000,...,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2021,2011-21,2021
4,Canada,0.001308,0.001757,0.001563,0.009377,0.005404,0.010593,0.043588,0.073661,0.155820,...,0.940541,0.931486,0.924823,0.914263,0.915107,0.884696,0.831268,-0.057817,-0.006322,0.03284
5,Mexico,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.107702,0.097725,0.100052,0.123889,0.101896,0.101413,0.107778,0.065671,0.011483,0.004258
6,US,0.039319,0.059354,0.082314,0.134714,0.149762,0.234456,0.409726,0.581625,0.897629,...,7.806465,7.843175,7.789835,7.764820,7.758474,7.543456,7.404259,-0.015764,-0.006798,0.29251
7,Total North America,0.040627,0.061111,0.083877,0.144092,0.155165,0.245049,0.453314,0.655286,1.053449,...,8.854708,8.872385,8.814710,8.802971,8.775477,8.529565,8.343304,-0.019157,-0.006536,0.329608
9,Argentina,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.065484,0.076619,0.055970,0.062809,0.076883,0.096736,0.097911,0.014919,0.048471,0.003868
10,Brazil,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.137072,0.146713,0.144699,0.143256,0.146870,0.127494,0.132921,0.045423,-0.011508,0.005251
11,Chile,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-,-,0
12,Colombia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-,-,0
13,Ecuador,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-,-,0

In [ ]:
print(Nuclear_cons.isnull().sum())

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [ ]:
#Setting the first row as the columns header and then dropping that row 
Nuclear_cons.columns = Nuclear_cons.iloc[0]
Nuclear_cons.reset_index(drop=True, inplace=True)
Nuclear_cons = Nuclear_cons.drop(axis=1, index=0)
Nuclear_cons.head(15)

2,Exajoules (input-equivalent),1965.0,1966.0,1967.0,1968.0,1969.0,1970.0,1971.0,1972.0,1973.0,...,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2021,2011-21,2021
1,Canada,0.001308,0.001757,0.001563,0.009377,0.005404,0.010593,0.043588,0.073661,0.155820,...,0.940541,0.931486,0.924823,0.914263,0.915107,0.884696,0.831268,-0.057817,-0.006322,0.03284
2,Mexico,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.107702,0.097725,0.100052,0.123889,0.101896,0.101413,0.107778,0.065671,0.011483,0.004258
3,US,0.039319,0.059354,0.082314,0.134714,0.149762,0.234456,0.409726,0.581625,0.897629,...,7.806465,7.843175,7.789835,7.764820,7.758474,7.543456,7.404259,-0.015764,-0.006798,0.29251
4,Total North America,0.040627,0.061111,0.083877,0.144092,0.155165,0.245049,0.453314,0.655286,1.053449,...,8.854708,8.872385,8.814710,8.802971,8.775477,8.529565,8.343304,-0.019157,-0.006536,0.329608
5,Argentina,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.065484,0.076619,0.055970,0.062809,0.076883,0.096736,0.097911,0.014919,0.048471,0.003868
6,Brazil,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.137072,0.146713,0.144699,0.143256,0.146870,0.127494,0.132921,0.045423,-0.011508,0.005251
7,Chile,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-,-,0
8,Colombia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-,-,0
9,Ecuador,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-,-,0
10,Peru,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-,-,0
11,Trinidad & Tobago,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-,-,0
12,Venezuela,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-,-,0
13,Central America,0.000000,0.000000,0.000000,0.000000,0.000521,0.000460,0.000429,0.000746,0.000470,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-,-,0
14,Other Caribbean,0.000000,0.000123,0.000388,0.000184,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-,-,0
15,Other South America,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-,-,0

In [ ]:
#dropping the last 3 columns which have calculated data that and is't part of the yearly energy consumption
Nuclear_cons=Nuclear_cons.iloc[:, :-3]
Nuclear_cons.columns

Index(['Exajoules (input-equivalent)',                         1965.0,
                               1966.0,                         1967.0,
                               1968.0,                         1969.0,
                               1970.0,                         1971.0,
                               1972.0,                         1973.0,
                               1974.0,                           1975,
                               1976.0,                         1977.0,
                               1978.0,                         1979.0,
                               1980.0,                         1981.0,
                               1982.0,                         1983.0,
                               1984.0,                         1985.0,
                               1986.0,                         1987.0,
                               1988.0,                         1989.0,
                               1990.0,                         1991.0,
                               1992.0,                         1993.0,
                               1994.0,                         1995.0,
                               1996.0,                         1997.0,
                               1998.0,                         1999.0,
                               2000.0,                         2001.0,
                               2002.0,                         2003.0,
                               2004.0,                         2005.0,
                               2006.0,                         2007.0,
                               2008.0,                         2009.0,
                               2010.0,                         2011.0,
                               2012.0,                         2013.0,
                               2014.0,                         2015.0,
                               2016.0,                         2017.0,
                               2018.0,                         2019.0,
                               2020.0,                         2021.0],
      dtype='object', name=2)

In [ ]:
#Changing the first column's name to "Country"
Nuclear_cons.rename(columns={"Exajoules (input-equivalent)": "Country"}, inplace=True)
Nuclear_cons.columns

Index(['Country',    1965.0,    1966.0,    1967.0,    1968.0,    1969.0,
          1970.0,    1971.0,    1972.0,    1973.0,    1974.0,      1975,
          1976.0,    1977.0,    1978.0,    1979.0,    1980.0,    1981.0,
          1982.0,    1983.0,    1984.0,    1985.0,    1986.0,    1987.0,
          1988.0,    1989.0,    1990.0,    1991.0,    1992.0,    1993.0,
          1994.0,    1995.0,    1996.0,    1997.0,    1998.0,    1999.0,
          2000.0,    2001.0,    2002.0,    2003.0,    2004.0,    2005.0,
          2006.0,    2007.0,    2008.0,    2009.0,    2010.0,    2011.0,
          2012.0,    2013.0,    2014.0,    2015.0,    2016.0,    2017.0,
          2018.0,    2019.0,    2020.0,    2021.0],
      dtype='object', name=2)

In [11]:
#Changing the type of the years column headers from float to integer
Nuclear_cons.columns = [int(col) if isinstance(col, float) else col for col in Nuclear_cons.columns]
Nuclear_cons.columns

Index(['Country',      1965,      1966,      1967,      1968,      1969,
            1970,      1971,      1972,      1973,      1974,      1975,
            1976,      1977,      1978,      1979,      1980,      1981,
            1982,      1983,      1984,      1985,      1986,      1987,
            1988,      1989,      1990,      1991,      1992,      1993,
            1994,      1995,      1996,      1997,      1998,      1999,
            2000,      2001,      2002,      2003,      2004,      2005,
            2006,      2007,      2008,      2009,      2010,      2011,
            2012,      2013,      2014,      2015,      2016,      2017,
            2018,      2019,      2020,      2021],
      dtype='object')

In [ ]:
cleaned_rows = []
rows = Nuclear_cons.reset_index(drop=True)

start_idx = 0

for idx, row in rows.iterrows():
    country = row['Country']
    # Extracting the region name when finding a total row
    if str(country).startswith("Total "):
        region = country.replace("Total ", "").strip()
        # Assigning this region to all rows from start_idx to idx - 1
        for j in range(start_idx, idx) :
            country_row = rows.iloc[j].copy()
            country_row['Region'] = region
            cleaned_rows.append(country_row)
        start_idx = idx + 1  # move start index to next group

In [13]:
# Create new DataFrame from cleaned list
Nuclear_cons = pd.DataFrame(cleaned_rows).reset_index(drop=True)

In [14]:
# Getting all year columns
year_columns = [col for col in Nuclear_cons.columns if isinstance(col, int)]

In [15]:
long_nuclear = pd.melt(
    Nuclear_cons,
    id_vars=['Country', 'Region'],          # keeping country and region
    value_vars=year_columns,                # years become rows
    var_name='Year',                        # new column name for former columns
    value_name='Nuclear Consumption (EJ)'    # name for the values
)

In [16]:
#Save this Dataset 
long_nuclear.to_csv('C:/Users/pc/Desktop/Formation Data Analyst/Projet/New Dataset/total_yearly_nuclear_consumption.csv', index=False)